### ISSUE TITLE
Sig_stat_pub.py is failing due to missing Socrautil Methods

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-publishing#230]
As noted [here](https://github.com/cityofaustin/atd-data-utilities/issues/7). Socratautil is missing needed methods, causing this script to fail.

Once socrautil is patched, we simply need to rebuild the `/tdp` docker image and deploy.

**Comment by johnclary** [comment]
Testing now with socratautil-dev `v0.0.5`. The method `NotFoundError` is resolved but I'm getting a `ValueError`:

```
Traceback (most recent call last):
  File "sig_stat_pub.py", line 170, in <module>
    main()
  File "sig_stat_pub.py", line 160, in main
    replace=False,
  File "/usr/local/lib/python3.6/site-packages/socratautil/socratautil.py", line 65, in __init__
    self._handle_records()
  File "/usr/local/lib/python3.6/site-packages/socratautil/socratautil.py", line 74, in _handle_records
    self.records = mills_to_unix(self.records, self.date_fields)
  File "/usr/local/lib/python3.6/site-packages/datautil/datautil.py", line 126, in mills_to_unix
    raise ValueError
ValueError
```
Will have to revisit tomorrow :(
